### ISSUE TITLE
Untitled file with contents "MEP: Sorry" automatically shows up after MATLAB startup

### ISSUE THREAD

**Issue by CloudyDory** [WickedChive/Matlab-Editor-Plugin#135]
Hello, thanks for this interesting tool.

I am using Matlab R2017b Update7. I have installed the tool according to setup guide, but I have noticed several issues.

Issue 1: Matlab automatically opens a untitled file with contents "MEP: Sorry" in editor after every Matlab startup.

Issue 2: Closing the last file in editor generate the following exceptions:
<details>  
<summary>Long stack trace</summary>

```none
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at at.mep.editor.EditorWrapper.getLongName(EditorWrapper.java:241)
	at at.mep.editor.EditorWrapper.getFile(EditorWrapper.java:269)
	at at.mep.editor.EditorWrapper.getFile(EditorWrapper.java:768)
	at at.mep.gui.AutoSwitcher.doYourThing(AutoSwitcher.java:35)
	at at.mep.editor.EditorApp$3.eventOccurred(EditorApp.java:241)
	at com.mathworks.mde.editor.MatlabEditor.fireEditorEvent(MatlabEditor.java:528)
	at com.mathworks.mde.editor.MatlabEditor.dispose(MatlabEditor.java:74)
	at com.mathworks.mde.editor.EditorViewClient.dispose(EditorViewClient.java:314)
	at com.mathworks.mde.editor.EditorViewClient$12.clientClosed(EditorViewClient.java:878)
	at com.mathworks.widgets.desk.DTClient.close(DTClient.java:905)
	at com.mathworks.widgets.desk.DTOccupant$2.closeReply(DTOccupant.java:869)
	at com.mathworks.widgets.desk.DTOccupant.doPropertyChange(DTOccupant.java:1166)
	at com.mathworks.widgets.desk.DTClient.doPropertyChange(DTClient.java:1495)
	at com.mathworks.widgets.desk.DTClient.propertyChange(DTClient.java:1463)
	at com.mathworks.widgets.desk.DTPropertyBridge$WeakLink.propertyChange(DTPropertyBridge.java:148)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8428)
	at javax.swing.JComponent.putClientProperty(JComponent.java:4087)
	at com.mathworks.widgets.desk.DTClientBase.approveClose(DTClientBase.java:328)
	at com.mathworks.mde.editor.EditorViewClient.approveDesktopClose(EditorViewClient.java:492)
	at com.mathworks.mde.editor.EditorViewClient.tryClosing(EditorViewClient.java:480)
	at com.mathworks.mde.editor.EditorViewClient.access$1400(EditorViewClient.java:79)
	at com.mathworks.mde.editor.EditorViewClient$12.clientClosing(EditorViewClient.java:866)
	at com.mathworks.widgets.desk.DTClient.canClose(DTClient.java:842)
	at com.mathworks.widgets.desk.DTOccupant.canClose(DTOccupant.java:867)
	at com.mathworks.widgets.desk.DTClient.attemptClose(DTClient.java:918)
	at com.mathworks.widgets.desk.DTClient$ClientCloseAction.actionPerformed(DTClient.java:1695)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at com.mathworks.mwswing.MJButton.processMouseEvent(MJButton.java:348)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```
</details>

-------------

Issue 3: Several short-cuts doesn't work, including "Ctrl+Shift+Y", "Alt+Shift+ArrowUp", "Alt+Shift+ArrowDown"; but "Ctrl+Shift+D" does work.

I don't know whether there is something wrong in my setup, or it is a bug. Hope somebody can help me.

**Comment by GavriYashar** [comment]
I'm sorry for the inconvenience
- Issue 1 and 2
  - the current design of MEP needs at least one editor open. 
- Issue 3
  - make sure the appropriate feature is enabled in the properties
  - are you still holding <kbd>CTRL</kbd> and <kbd>SHIFT</kbd> on the release of <kbd>Y</kbd>?
